### ISSUE TITLE
How to use this project？

### ISSUE THREAD

**Issue by OSCARXDWU** [emfarih/Leader-Follower-Navigation-System-based-on-Pedestrian-Dead-Reckoning-for-Mobile-Robot-Navigation#1]
Dear friend,
    I'm interested in this project. Is this a project to be used with all the five folders?  Or could it be used with anyone of the five folders? 
    For example, I want a simulation with the matlab. But it can't run with only the matlab codes.
    So can this project run only with the matlab? And how to use it with some tutorials.
Thank you!

**Comment by emfarih** [comment]
Hi @abc283646346 ,

This project won't do only using Matlab. Matlab in this project is used just for training the step model. All the data are obtained from real IMU devices sensor. You can read this paper for more insight about this project. https://ieeexplore.ieee.org/document/8937138

Thank you
